;;;; codegen/lisp-generator.lisp
;;;; Converts parsed C declarations to CFFI Lisp forms.

(in-package #:cl-webgpu-codegen)

;;; Primitive C → CFFI type mapping

(defparameter *primitive-type-map*
  '(("void"              . ":void")
    ("uint8_t"           . ":uint8")
    ("uint16_t"          . ":uint16")
    ("uint32_t"          . ":uint32")
    ("uint64_t"          . ":uint64")
    ("int8_t"            . ":int8")
    ("int16_t"           . ":int16")
    ("int32_t"           . ":int32")
    ("int64_t"           . ":int64")
    ("size_t"            . ":size")
    ("float"             . ":float")
    ("double"            . ":double")
    ("bool"              . ":bool")
    ("WGPUBool"          . "wgpu-bool")
    ("WGPUFlags"         . "wgpu-flags")
    ("WGPUProc"          . "wgpu-proc")
    ;; wgpu-native specific
    ("WGPUSubmissionIndex" . ":uint64")))

(defun resolve-cffi-type (c-type ctx)
  "Resolve a C type string to its CFFI type form string.
  CTX is the parse-context with known type registries."
  (let* ((raw (string-trim '(#\space #\tab) c-type))
         (is-ptr (pointer-type-p raw))
         (base (string-trim '(#\space #\tab) (base-type raw))))
    (cond
      (is-ptr ":pointer")
      ((assoc base *primitive-type-map* :test #'string=)
       (cdr (assoc base *primitive-type-map* :test #'string=)))
      ((gethash base (parse-context-opaque-handles ctx))
       (c-type-name-to-symbol base))
      ((gethash base (parse-context-enum-types ctx))
       (c-type-name-to-symbol base))
      ((gethash base (parse-context-flag-types ctx))
       "wgpu-flags")
      ((gethash base (parse-context-struct-types ctx))
       (format nil "(:struct ~A)" (c-type-name-to-symbol base)))
      (t ":pointer"))))

(defun struct-by-value-p (c-type ctx)
  "Return true if C-TYPE is a struct passed by value (problematic for CFFI)."
  (let* ((raw (string-trim '(#\space #\tab) c-type))
         (is-ptr (pointer-type-p raw))
         (base (string-trim '(#\space #\tab) (base-type raw))))
    (and (not is-ptr)
         (gethash base (parse-context-struct-types ctx))
         ;; WGPUBool / WGPUFlags are typedefs to primitives, not real structs
         (not (assoc base *primitive-type-map* :test #'string=)))))

(defun function-problematic-p (decl ctx)
  "Return a reason string if this function can't be directly bound, else nil."
  (let ((ret (getf decl :return-type))
        (params (getf decl :params)))
    (cond
      ((struct-by-value-p ret ctx)
       (format nil "returns ~A by value" ret))
      ((some (lambda (p) (struct-by-value-p (getf p :ctype) ctx)) params)
       (let ((bad (find-if (lambda (p) (struct-by-value-p (getf p :ctype) ctx)) params)))
         (format nil "param ~A is ~A by value" (getf bad :name) (getf bad :ctype))))
      (t nil))))

;;; Output helpers

(defun write-section-header (out title)
  (format out "~%;; ~69,,,'-<~>~%;; ~A~%;; ~69,,,'-<~>~%~%" title))

(defun write-preamble (out filename)
  (format out ";;;; ~A~%" filename)
  (format out ";;;; AUTO-GENERATED by cl-webgpu-codegen. Do not edit manually.~%")
  (format out ";;;; Run (cl-webgpu-codegen:generate) to regenerate.~%~%")
  (format out "(in-package #:cl-webgpu)~%"))

;;; Generators for each declaration kind

(defun gen-opaque (decl out)
  (format out "(defctype ~A :pointer)~%" (c-type-name-to-symbol (getf decl :name))))

(defun gen-enum (decl out)
  (let ((name (c-type-name-to-symbol (getf decl :name)))
        (values (getf decl :values)))
    (if (null values)
        (format out ";; (defcenum ~A) ; no values~%" name)
        (progn
          (format out "(defcenum ~A~%" name)
          (loop for (c-val-name . val) in values
                for i from 0
                for kw = (c-enum-value-to-keyword-string (getf decl :name) c-val-name)
                do (if (= i (1- (length values)))
                       (format out "  (:~A #x~X))~%" kw val)
                       (format out "  (:~A #x~X)~%" kw val)))))))

(defun gen-flag-group (declarations flag-type-name out)
  "Emit all flag constants for a given flag type."
  (let ((type-sym (c-type-name-to-symbol flag-type-name)))
    (format out "~%;; ~A flags~%" type-sym)
    (dolist (decl declarations)
      (when (and (eq (getf decl :kind) :flag-value)
                 (string= (getf decl :flag-type) flag-type-name))
        (let* ((constant-str (c-flag-name-to-constant-string (getf decl :name)))
               (val (getf decl :value)))
          (format out "(defconstant ~A~A)~%"
                  constant-str
                  (if (= val 0)
                      " 0"
                      (format nil " #x~X" val))))))))

(defun gen-struct (decl ctx out)
  (let ((name (c-type-name-to-symbol (getf decl :name)))
        (fields (getf decl :fields)))
    (if (null fields)
        (format out "(defcstruct ~A)~%" name)
        (progn
          (format out "(defcstruct ~A~%" name)
          (loop for field in fields
                for i from 0
                for field-sym = (c-field-name-to-symbol (getf field :name))
                for cffi-type = (resolve-cffi-type (getf field :ctype) ctx)
                do (if (= i (1- (length fields)))
                       (format out "  (~A ~A))~%" field-sym cffi-type)
                       (format out "  (~A ~A)~%" field-sym cffi-type)))))))

(defun gen-function (decl ctx out)
  (let* ((c-name (getf decl :name))
         (lisp-name (c-name-to-lisp-symbol c-name))
         (ret-cffi (resolve-cffi-type (getf decl :return-type) ctx))
         (params (getf decl :params))
         (reason (function-problematic-p decl ctx)))
    (if reason
        (format out "~%;; NOTE: ~A skipped (~A) - use shim~%" lisp-name reason)
        (if (null params)
            (format out "~%(defcfun (~S ~A) ~A)~%" c-name lisp-name ret-cffi)
            (progn
              (format out "~%(defcfun (~S ~A) ~A~%" c-name lisp-name ret-cffi)
              (loop for p in params
                    for i from 0
                    for p-sym = (c-field-name-to-symbol (getf p :name))
                    for p-type = (resolve-cffi-type (getf p :ctype) ctx)
                    do (if (= i (1- (length params)))
                           (format out "  (~A ~A))~%" p-sym p-type)
                           (format out "  (~A ~A)~%" p-sym p-type))))))))

;;; Main generation functions

(defun generate-types-file (ctx out)
  "Write src/types.lisp content to OUT stream."
  (write-preamble out "types.lisp")
  (let ((decls (parse-context-declarations ctx)))

    (write-section-header out "Opaque handle types")
    (dolist (d decls)
      (when (eq (getf d :kind) :opaque)
        (gen-opaque d out)))

    ;; Emit WGPUFlags, WGPUBool, WGPUProc type aliases
    (terpri out)
    (format out ";; Type aliases~%")
    (format out "(defctype wgpu-flags :uint64)~%")
    (format out "(defctype wgpu-bool :uint32)~%")
    (format out "(defctype wgpu-proc :pointer)~%")

    (write-section-header out "Enumerations")
    (dolist (d decls)
      (when (eq (getf d :kind) :enum)
        (gen-enum d out)
        (terpri out)))

    (write-section-header out "Bitflag constants")
    ;; Collect all flag types in order, emit each group
    (let ((seen-flag-types '()))
      (dolist (d decls)
        (when (eq (getf d :kind) :flag-type)
          (unless (member (getf d :name) seen-flag-types :test #'string=)
            (push (getf d :name) seen-flag-types)
            (gen-flag-group decls (getf d :name) out)))))

    (write-section-header out "Structures")
    (dolist (d decls)
      (when (eq (getf d :kind) :struct)
        (gen-struct d ctx out)
        (terpri out)))))

(defun generate-functions-file (ctx out)
  "Write src/functions.lisp content to OUT stream."
  (write-preamble out "functions.lisp")
  (let ((decls (parse-context-declarations ctx)))
    (dolist (d decls)
      (when (eq (getf d :kind) :function)
        (gen-function d ctx out)))))

;;; Package file generation

(defparameter *static-extra-exports*
  '("load-wgpu-libraries"
    "wgpu-shim-make-string-view")
  "Symbols from hand-maintained files that should always be exported.")

(defun collect-export-symbols (ctx)
  "Return a sorted list of symbol name strings to export from cl-webgpu."
  (let ((syms '())
        (decls (parse-context-declarations ctx)))
    ;; Opaque handles, enum types, struct types, flag types → their type symbol names
    (dolist (d decls)
      (case (getf d :kind)
        ((:opaque :enum :struct :flag-type)
         (push (c-type-name-to-symbol (getf d :name)) syms))
        (:flag-value
         (push (c-flag-name-to-constant-string (getf d :name)) syms))
        (:function
         (unless (function-problematic-p d ctx)
           (push (c-name-to-lisp-symbol (getf d :name)) syms)))))
    ;; Type aliases always present
    (dolist (alias '("wgpu-flags" "wgpu-bool" "wgpu-proc"))
      (push alias syms))
    ;; Hand-maintained extras
    (dolist (extra *static-extra-exports*)
      (push extra syms))
    (sort (remove-duplicates syms :test #'string=) #'string<)))

(defun generate-package-file (ctx out)
  "Write src/package.lisp content to OUT stream."
  (format out ";;;; package.lisp~%")
  (format out ";;;; AUTO-GENERATED by cl-webgpu-codegen. Do not edit manually.~%")
  (format out ";;;; Run (cl-webgpu-codegen:generate) to regenerate.~%~%")
  (format out "(defpackage #:cl-webgpu~%")
  (format out "  (:use #:cl #:cffi)~%")
  (format out "  (:export~%")
  (let ((exports (collect-export-symbols ctx)))
    (loop for sym in exports
          for i from 0
          do (if (= i (1- (length exports)))
                 (format out "   #:~A))~%" sym)
                 (format out "   #:~A~%" sym)))))
