;;;; functions.lisp
;;;; AUTO-GENERATED by cl-webgpu-codegen. Do not edit manually.
;;;; Run (cl-webgpu-codegen:generate) to regenerate.

(in-package #:cl-webgpu)

(defcfun ("wgpuCreateInstance" wgpu-create-instance) wgpu-instance
  (descriptor :pointer))

(defcfun ("wgpuGetInstanceFeatures" wgpu-get-instance-features) :void
  (features :pointer))

(defcfun ("wgpuGetInstanceLimits" wgpu-get-instance-limits) wgpu-status
  (limits :pointer))

(defcfun ("wgpuHasInstanceFeature" wgpu-has-instance-feature) wgpu-bool
  (feature wgpu-instance-feature-name))

;; NOTE: wgpu-get-proc-address skipped (param procName is WGPUStringView by value) - use shim

(defcfun ("wgpuAdapterGetFeatures" wgpu-adapter-get-features) :void
  (adapter wgpu-adapter)
  (features :pointer))

(defcfun ("wgpuAdapterGetInfo" wgpu-adapter-get-info) wgpu-status
  (adapter wgpu-adapter)
  (info :pointer))

(defcfun ("wgpuAdapterGetLimits" wgpu-adapter-get-limits) wgpu-status
  (adapter wgpu-adapter)
  (limits :pointer))

(defcfun ("wgpuAdapterHasFeature" wgpu-adapter-has-feature) wgpu-bool
  (adapter wgpu-adapter)
  (feature wgpu-feature-name))

;; NOTE: wgpu-adapter-request-device skipped (returns WGPUFuture by value) - use shim

(defcfun ("wgpuAdapterAddRef" wgpu-adapter-add-ref) :void
  (adapter wgpu-adapter))

(defcfun ("wgpuAdapterRelease" wgpu-adapter-release) :void
  (adapter wgpu-adapter))

;; NOTE: wgpu-adapter-info-free-members skipped (param adapterInfo is WGPUAdapterInfo by value) - use shim

;; NOTE: wgpu-bind-group-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuBindGroupAddRef" wgpu-bind-group-add-ref) :void
  (bind-group wgpu-bind-group))

(defcfun ("wgpuBindGroupRelease" wgpu-bind-group-release) :void
  (bind-group wgpu-bind-group))

;; NOTE: wgpu-bind-group-layout-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuBindGroupLayoutAddRef" wgpu-bind-group-layout-add-ref) :void
  (bind-group-layout wgpu-bind-group-layout))

(defcfun ("wgpuBindGroupLayoutRelease" wgpu-bind-group-layout-release) :void
  (bind-group-layout wgpu-bind-group-layout))

(defcfun ("wgpuBufferDestroy" wgpu-buffer-destroy) :void
  (buffer wgpu-buffer))

(defcfun ("wgpuBufferGetConstMappedRange" wgpu-buffer-get-const-mapped-range) :pointer
  (buffer wgpu-buffer)
  (offset :size)
  (size :size))

(defcfun ("wgpuBufferGetMappedRange" wgpu-buffer-get-mapped-range) :pointer
  (buffer wgpu-buffer)
  (offset :size)
  (size :size))

(defcfun ("wgpuBufferGetMapState" wgpu-buffer-get-map-state) wgpu-buffer-map-state
  (buffer wgpu-buffer))

(defcfun ("wgpuBufferGetSize" wgpu-buffer-get-size) :uint64
  (buffer wgpu-buffer))

(defcfun ("wgpuBufferGetUsage" wgpu-buffer-get-usage) wgpu-flags
  (buffer wgpu-buffer))

;; NOTE: wgpu-buffer-map-async skipped (returns WGPUFuture by value) - use shim

(defcfun ("wgpuBufferReadMappedRange" wgpu-buffer-read-mapped-range) wgpu-status
  (buffer wgpu-buffer)
  (offset :size)
  (data :pointer)
  (size :size))

;; NOTE: wgpu-buffer-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuBufferUnmap" wgpu-buffer-unmap) :void
  (buffer wgpu-buffer))

(defcfun ("wgpuBufferWriteMappedRange" wgpu-buffer-write-mapped-range) wgpu-status
  (buffer wgpu-buffer)
  (offset :size)
  (data :pointer)
  (size :size))

(defcfun ("wgpuBufferAddRef" wgpu-buffer-add-ref) :void
  (buffer wgpu-buffer))

(defcfun ("wgpuBufferRelease" wgpu-buffer-release) :void
  (buffer wgpu-buffer))

;; NOTE: wgpu-command-buffer-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuCommandBufferAddRef" wgpu-command-buffer-add-ref) :void
  (command-buffer wgpu-command-buffer))

(defcfun ("wgpuCommandBufferRelease" wgpu-command-buffer-release) :void
  (command-buffer wgpu-command-buffer))

(defcfun ("wgpuCommandEncoderBeginComputePass" wgpu-command-encoder-begin-compute-pass) wgpu-compute-pass-encoder
  (command-encoder wgpu-command-encoder)
  (descriptor :pointer))

(defcfun ("wgpuCommandEncoderBeginRenderPass" wgpu-command-encoder-begin-render-pass) wgpu-render-pass-encoder
  (command-encoder wgpu-command-encoder)
  (descriptor :pointer))

(defcfun ("wgpuCommandEncoderClearBuffer" wgpu-command-encoder-clear-buffer) :void
  (command-encoder wgpu-command-encoder)
  (buffer wgpu-buffer)
  (offset :uint64)
  (size :uint64))

(defcfun ("wgpuCommandEncoderCopyBufferToBuffer" wgpu-command-encoder-copy-buffer-to-buffer) :void
  (command-encoder wgpu-command-encoder)
  (source wgpu-buffer)
  (source-offset :uint64)
  (destination wgpu-buffer)
  (destination-offset :uint64)
  (size :uint64))

(defcfun ("wgpuCommandEncoderCopyBufferToTexture" wgpu-command-encoder-copy-buffer-to-texture) :void
  (command-encoder wgpu-command-encoder)
  (source :pointer)
  (destination :pointer)
  (copy-size :pointer))

(defcfun ("wgpuCommandEncoderCopyTextureToBuffer" wgpu-command-encoder-copy-texture-to-buffer) :void
  (command-encoder wgpu-command-encoder)
  (source :pointer)
  (destination :pointer)
  (copy-size :pointer))

(defcfun ("wgpuCommandEncoderCopyTextureToTexture" wgpu-command-encoder-copy-texture-to-texture) :void
  (command-encoder wgpu-command-encoder)
  (source :pointer)
  (destination :pointer)
  (copy-size :pointer))

(defcfun ("wgpuCommandEncoderFinish" wgpu-command-encoder-finish) wgpu-command-buffer
  (command-encoder wgpu-command-encoder)
  (descriptor :pointer))

;; NOTE: wgpu-command-encoder-insert-debug-marker skipped (param markerLabel is WGPUStringView by value) - use shim

(defcfun ("wgpuCommandEncoderPopDebugGroup" wgpu-command-encoder-pop-debug-group) :void
  (command-encoder wgpu-command-encoder))

;; NOTE: wgpu-command-encoder-push-debug-group skipped (param groupLabel is WGPUStringView by value) - use shim

(defcfun ("wgpuCommandEncoderResolveQuerySet" wgpu-command-encoder-resolve-query-set) :void
  (command-encoder wgpu-command-encoder)
  (query-set wgpu-query-set)
  (first-query :uint32)
  (query-count :uint32)
  (destination wgpu-buffer)
  (destination-offset :uint64))

;; NOTE: wgpu-command-encoder-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuCommandEncoderWriteTimestamp" wgpu-command-encoder-write-timestamp) :void
  (command-encoder wgpu-command-encoder)
  (query-set wgpu-query-set)
  (query-index :uint32))

(defcfun ("wgpuCommandEncoderAddRef" wgpu-command-encoder-add-ref) :void
  (command-encoder wgpu-command-encoder))

(defcfun ("wgpuCommandEncoderRelease" wgpu-command-encoder-release) :void
  (command-encoder wgpu-command-encoder))

(defcfun ("wgpuComputePassEncoderDispatchWorkgroups" wgpu-compute-pass-encoder-dispatch-workgroups) :void
  (compute-pass-encoder wgpu-compute-pass-encoder)
  (workgroup-count-x :uint32)
  (workgroup-count-y :uint32)
  (workgroup-count-z :uint32))

(defcfun ("wgpuComputePassEncoderDispatchWorkgroupsIndirect" wgpu-compute-pass-encoder-dispatch-workgroups-indirect) :void
  (compute-pass-encoder wgpu-compute-pass-encoder)
  (indirect-buffer wgpu-buffer)
  (indirect-offset :uint64))

(defcfun ("wgpuComputePassEncoderEnd" wgpu-compute-pass-encoder-end) :void
  (compute-pass-encoder wgpu-compute-pass-encoder))

;; NOTE: wgpu-compute-pass-encoder-insert-debug-marker skipped (param markerLabel is WGPUStringView by value) - use shim

(defcfun ("wgpuComputePassEncoderPopDebugGroup" wgpu-compute-pass-encoder-pop-debug-group) :void
  (compute-pass-encoder wgpu-compute-pass-encoder))

;; NOTE: wgpu-compute-pass-encoder-push-debug-group skipped (param groupLabel is WGPUStringView by value) - use shim

(defcfun ("wgpuComputePassEncoderSetBindGroup" wgpu-compute-pass-encoder-set-bind-group) :void
  (compute-pass-encoder wgpu-compute-pass-encoder)
  (group-index :uint32)
  (group wgpu-bind-group)
  (dynamic-offset-count :size)
  (dynamic-offsets :pointer))

(defcfun ("wgpuComputePassEncoderSetImmediates" wgpu-compute-pass-encoder-set-immediates) :void
  (compute-pass-encoder wgpu-compute-pass-encoder)
  (offset :uint32)
  (data :pointer)
  (size :size))

;; NOTE: wgpu-compute-pass-encoder-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuComputePassEncoderSetPipeline" wgpu-compute-pass-encoder-set-pipeline) :void
  (compute-pass-encoder wgpu-compute-pass-encoder)
  (pipeline wgpu-compute-pipeline))

(defcfun ("wgpuComputePassEncoderAddRef" wgpu-compute-pass-encoder-add-ref) :void
  (compute-pass-encoder wgpu-compute-pass-encoder))

(defcfun ("wgpuComputePassEncoderRelease" wgpu-compute-pass-encoder-release) :void
  (compute-pass-encoder wgpu-compute-pass-encoder))

(defcfun ("wgpuComputePipelineGetBindGroupLayout" wgpu-compute-pipeline-get-bind-group-layout) wgpu-bind-group-layout
  (compute-pipeline wgpu-compute-pipeline)
  (group-index :uint32))

;; NOTE: wgpu-compute-pipeline-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuComputePipelineAddRef" wgpu-compute-pipeline-add-ref) :void
  (compute-pipeline wgpu-compute-pipeline))

(defcfun ("wgpuComputePipelineRelease" wgpu-compute-pipeline-release) :void
  (compute-pipeline wgpu-compute-pipeline))

(defcfun ("wgpuDeviceCreateBindGroup" wgpu-device-create-bind-group) wgpu-bind-group
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuDeviceCreateBindGroupLayout" wgpu-device-create-bind-group-layout) wgpu-bind-group-layout
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuDeviceCreateBuffer" wgpu-device-create-buffer) wgpu-buffer
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuDeviceCreateCommandEncoder" wgpu-device-create-command-encoder) wgpu-command-encoder
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuDeviceCreateComputePipeline" wgpu-device-create-compute-pipeline) wgpu-compute-pipeline
  (device wgpu-device)
  (descriptor :pointer))

;; NOTE: wgpu-device-create-compute-pipeline-async skipped (returns WGPUFuture by value) - use shim

(defcfun ("wgpuDeviceCreatePipelineLayout" wgpu-device-create-pipeline-layout) wgpu-pipeline-layout
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuDeviceCreateQuerySet" wgpu-device-create-query-set) wgpu-query-set
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuDeviceCreateRenderBundleEncoder" wgpu-device-create-render-bundle-encoder) wgpu-render-bundle-encoder
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuDeviceCreateRenderPipeline" wgpu-device-create-render-pipeline) wgpu-render-pipeline
  (device wgpu-device)
  (descriptor :pointer))

;; NOTE: wgpu-device-create-render-pipeline-async skipped (returns WGPUFuture by value) - use shim

(defcfun ("wgpuDeviceCreateSampler" wgpu-device-create-sampler) wgpu-sampler
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuDeviceCreateShaderModule" wgpu-device-create-shader-module) wgpu-shader-module
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuDeviceCreateTexture" wgpu-device-create-texture) wgpu-texture
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuDeviceDestroy" wgpu-device-destroy) :void
  (device wgpu-device))

(defcfun ("wgpuDeviceGetAdapterInfo" wgpu-device-get-adapter-info) wgpu-status
  (device wgpu-device)
  (adapter-info :pointer))

(defcfun ("wgpuDeviceGetFeatures" wgpu-device-get-features) :void
  (device wgpu-device)
  (features :pointer))

(defcfun ("wgpuDeviceGetLimits" wgpu-device-get-limits) wgpu-status
  (device wgpu-device)
  (limits :pointer))

;; NOTE: wgpu-device-get-lost-future skipped (returns WGPUFuture by value) - use shim

(defcfun ("wgpuDeviceGetQueue" wgpu-device-get-queue) wgpu-queue
  (device wgpu-device))

(defcfun ("wgpuDeviceHasFeature" wgpu-device-has-feature) wgpu-bool
  (device wgpu-device)
  (feature wgpu-feature-name))

;; NOTE: wgpu-device-pop-error-scope skipped (returns WGPUFuture by value) - use shim

(defcfun ("wgpuDevicePushErrorScope" wgpu-device-push-error-scope) :void
  (device wgpu-device)
  (filter wgpu-error-filter))

;; NOTE: wgpu-device-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuDeviceAddRef" wgpu-device-add-ref) :void
  (device wgpu-device))

(defcfun ("wgpuDeviceRelease" wgpu-device-release) :void
  (device wgpu-device))

;; NOTE: wgpu-external-texture-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuExternalTextureAddRef" wgpu-external-texture-add-ref) :void
  (external-texture wgpu-external-texture))

(defcfun ("wgpuExternalTextureRelease" wgpu-external-texture-release) :void
  (external-texture wgpu-external-texture))

(defcfun ("wgpuInstanceCreateSurface" wgpu-instance-create-surface) wgpu-surface
  (instance wgpu-instance)
  (descriptor :pointer))

(defcfun ("wgpuInstanceGetWGSLLanguageFeatures" wgpu-instance-get-wgsl-language-features) :void
  (instance wgpu-instance)
  (features :pointer))

(defcfun ("wgpuInstanceHasWGSLLanguageFeature" wgpu-instance-has-wgsl-language-feature) wgpu-bool
  (instance wgpu-instance)
  (feature wgpu-wgsl-language-feature-name))

(defcfun ("wgpuInstanceProcessEvents" wgpu-instance-process-events) :void
  (instance wgpu-instance))

;; NOTE: wgpu-instance-request-adapter skipped (returns WGPUFuture by value) - use shim

(defcfun ("wgpuInstanceWaitAny" wgpu-instance-wait-any) wgpu-wait-status
  (instance wgpu-instance)
  (future-count :size)
  (futures :pointer)
  (timeout-ns :uint64))

(defcfun ("wgpuInstanceAddRef" wgpu-instance-add-ref) :void
  (instance wgpu-instance))

(defcfun ("wgpuInstanceRelease" wgpu-instance-release) :void
  (instance wgpu-instance))

;; NOTE: wgpu-pipeline-layout-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuPipelineLayoutAddRef" wgpu-pipeline-layout-add-ref) :void
  (pipeline-layout wgpu-pipeline-layout))

(defcfun ("wgpuPipelineLayoutRelease" wgpu-pipeline-layout-release) :void
  (pipeline-layout wgpu-pipeline-layout))

(defcfun ("wgpuQuerySetDestroy" wgpu-query-set-destroy) :void
  (query-set wgpu-query-set))

(defcfun ("wgpuQuerySetGetCount" wgpu-query-set-get-count) :uint32
  (query-set wgpu-query-set))

(defcfun ("wgpuQuerySetGetType" wgpu-query-set-get-type) wgpu-query-type
  (query-set wgpu-query-set))

;; NOTE: wgpu-query-set-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuQuerySetAddRef" wgpu-query-set-add-ref) :void
  (query-set wgpu-query-set))

(defcfun ("wgpuQuerySetRelease" wgpu-query-set-release) :void
  (query-set wgpu-query-set))

;; NOTE: wgpu-queue-on-submitted-work-done skipped (returns WGPUFuture by value) - use shim

;; NOTE: wgpu-queue-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuQueueSubmit" wgpu-queue-submit) :void
  (queue wgpu-queue)
  (command-count :size)
  (commands :pointer))

(defcfun ("wgpuQueueWriteBuffer" wgpu-queue-write-buffer) :void
  (queue wgpu-queue)
  (buffer wgpu-buffer)
  (buffer-offset :uint64)
  (data :pointer)
  (size :size))

(defcfun ("wgpuQueueWriteTexture" wgpu-queue-write-texture) :void
  (queue wgpu-queue)
  (destination :pointer)
  (data :pointer)
  (data-size :size)
  (data-layout :pointer)
  (write-size :pointer))

(defcfun ("wgpuQueueAddRef" wgpu-queue-add-ref) :void
  (queue wgpu-queue))

(defcfun ("wgpuQueueRelease" wgpu-queue-release) :void
  (queue wgpu-queue))

;; NOTE: wgpu-render-bundle-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuRenderBundleAddRef" wgpu-render-bundle-add-ref) :void
  (render-bundle wgpu-render-bundle))

(defcfun ("wgpuRenderBundleRelease" wgpu-render-bundle-release) :void
  (render-bundle wgpu-render-bundle))

(defcfun ("wgpuRenderBundleEncoderDraw" wgpu-render-bundle-encoder-draw) :void
  (render-bundle-encoder wgpu-render-bundle-encoder)
  (vertex-count :uint32)
  (instance-count :uint32)
  (first-vertex :uint32)
  (first-instance :uint32))

(defcfun ("wgpuRenderBundleEncoderDrawIndexed" wgpu-render-bundle-encoder-draw-indexed) :void
  (render-bundle-encoder wgpu-render-bundle-encoder)
  (index-count :uint32)
  (instance-count :uint32)
  (first-index :uint32)
  (base-vertex :int32)
  (first-instance :uint32))

(defcfun ("wgpuRenderBundleEncoderDrawIndexedIndirect" wgpu-render-bundle-encoder-draw-indexed-indirect) :void
  (render-bundle-encoder wgpu-render-bundle-encoder)
  (indirect-buffer wgpu-buffer)
  (indirect-offset :uint64))

(defcfun ("wgpuRenderBundleEncoderDrawIndirect" wgpu-render-bundle-encoder-draw-indirect) :void
  (render-bundle-encoder wgpu-render-bundle-encoder)
  (indirect-buffer wgpu-buffer)
  (indirect-offset :uint64))

(defcfun ("wgpuRenderBundleEncoderFinish" wgpu-render-bundle-encoder-finish) wgpu-render-bundle
  (render-bundle-encoder wgpu-render-bundle-encoder)
  (descriptor :pointer))

;; NOTE: wgpu-render-bundle-encoder-insert-debug-marker skipped (param markerLabel is WGPUStringView by value) - use shim

(defcfun ("wgpuRenderBundleEncoderPopDebugGroup" wgpu-render-bundle-encoder-pop-debug-group) :void
  (render-bundle-encoder wgpu-render-bundle-encoder))

;; NOTE: wgpu-render-bundle-encoder-push-debug-group skipped (param groupLabel is WGPUStringView by value) - use shim

(defcfun ("wgpuRenderBundleEncoderSetBindGroup" wgpu-render-bundle-encoder-set-bind-group) :void
  (render-bundle-encoder wgpu-render-bundle-encoder)
  (group-index :uint32)
  (group wgpu-bind-group)
  (dynamic-offset-count :size)
  (dynamic-offsets :pointer))

(defcfun ("wgpuRenderBundleEncoderSetImmediates" wgpu-render-bundle-encoder-set-immediates) :void
  (render-bundle-encoder wgpu-render-bundle-encoder)
  (offset :uint32)
  (data :pointer)
  (size :size))

(defcfun ("wgpuRenderBundleEncoderSetIndexBuffer" wgpu-render-bundle-encoder-set-index-buffer) :void
  (render-bundle-encoder wgpu-render-bundle-encoder)
  (buffer wgpu-buffer)
  (format wgpu-index-format)
  (offset :uint64)
  (size :uint64))

;; NOTE: wgpu-render-bundle-encoder-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuRenderBundleEncoderSetPipeline" wgpu-render-bundle-encoder-set-pipeline) :void
  (render-bundle-encoder wgpu-render-bundle-encoder)
  (pipeline wgpu-render-pipeline))

(defcfun ("wgpuRenderBundleEncoderSetVertexBuffer" wgpu-render-bundle-encoder-set-vertex-buffer) :void
  (render-bundle-encoder wgpu-render-bundle-encoder)
  (slot :uint32)
  (buffer wgpu-buffer)
  (offset :uint64)
  (size :uint64))

(defcfun ("wgpuRenderBundleEncoderAddRef" wgpu-render-bundle-encoder-add-ref) :void
  (render-bundle-encoder wgpu-render-bundle-encoder))

(defcfun ("wgpuRenderBundleEncoderRelease" wgpu-render-bundle-encoder-release) :void
  (render-bundle-encoder wgpu-render-bundle-encoder))

(defcfun ("wgpuRenderPassEncoderBeginOcclusionQuery" wgpu-render-pass-encoder-begin-occlusion-query) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (query-index :uint32))

(defcfun ("wgpuRenderPassEncoderDraw" wgpu-render-pass-encoder-draw) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (vertex-count :uint32)
  (instance-count :uint32)
  (first-vertex :uint32)
  (first-instance :uint32))

(defcfun ("wgpuRenderPassEncoderDrawIndexed" wgpu-render-pass-encoder-draw-indexed) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (index-count :uint32)
  (instance-count :uint32)
  (first-index :uint32)
  (base-vertex :int32)
  (first-instance :uint32))

(defcfun ("wgpuRenderPassEncoderDrawIndexedIndirect" wgpu-render-pass-encoder-draw-indexed-indirect) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (indirect-buffer wgpu-buffer)
  (indirect-offset :uint64))

(defcfun ("wgpuRenderPassEncoderDrawIndirect" wgpu-render-pass-encoder-draw-indirect) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (indirect-buffer wgpu-buffer)
  (indirect-offset :uint64))

(defcfun ("wgpuRenderPassEncoderEnd" wgpu-render-pass-encoder-end) :void
  (render-pass-encoder wgpu-render-pass-encoder))

(defcfun ("wgpuRenderPassEncoderEndOcclusionQuery" wgpu-render-pass-encoder-end-occlusion-query) :void
  (render-pass-encoder wgpu-render-pass-encoder))

(defcfun ("wgpuRenderPassEncoderExecuteBundles" wgpu-render-pass-encoder-execute-bundles) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (bundle-count :size)
  (bundles :pointer))

;; NOTE: wgpu-render-pass-encoder-insert-debug-marker skipped (param markerLabel is WGPUStringView by value) - use shim

(defcfun ("wgpuRenderPassEncoderPopDebugGroup" wgpu-render-pass-encoder-pop-debug-group) :void
  (render-pass-encoder wgpu-render-pass-encoder))

;; NOTE: wgpu-render-pass-encoder-push-debug-group skipped (param groupLabel is WGPUStringView by value) - use shim

(defcfun ("wgpuRenderPassEncoderSetBindGroup" wgpu-render-pass-encoder-set-bind-group) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (group-index :uint32)
  (group wgpu-bind-group)
  (dynamic-offset-count :size)
  (dynamic-offsets :pointer))

(defcfun ("wgpuRenderPassEncoderSetBlendConstant" wgpu-render-pass-encoder-set-blend-constant) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (color :pointer))

(defcfun ("wgpuRenderPassEncoderSetImmediates" wgpu-render-pass-encoder-set-immediates) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (offset :uint32)
  (data :pointer)
  (size :size))

(defcfun ("wgpuRenderPassEncoderSetIndexBuffer" wgpu-render-pass-encoder-set-index-buffer) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (buffer wgpu-buffer)
  (format wgpu-index-format)
  (offset :uint64)
  (size :uint64))

;; NOTE: wgpu-render-pass-encoder-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuRenderPassEncoderSetPipeline" wgpu-render-pass-encoder-set-pipeline) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (pipeline wgpu-render-pipeline))

(defcfun ("wgpuRenderPassEncoderSetScissorRect" wgpu-render-pass-encoder-set-scissor-rect) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (x :uint32)
  (y :uint32)
  (width :uint32)
  (height :uint32))

(defcfun ("wgpuRenderPassEncoderSetStencilReference" wgpu-render-pass-encoder-set-stencil-reference) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (reference :uint32))

(defcfun ("wgpuRenderPassEncoderSetVertexBuffer" wgpu-render-pass-encoder-set-vertex-buffer) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (slot :uint32)
  (buffer wgpu-buffer)
  (offset :uint64)
  (size :uint64))

(defcfun ("wgpuRenderPassEncoderSetViewport" wgpu-render-pass-encoder-set-viewport) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (x :float)
  (y :float)
  (width :float)
  (height :float)
  (min-depth :float)
  (max-depth :float))

(defcfun ("wgpuRenderPassEncoderAddRef" wgpu-render-pass-encoder-add-ref) :void
  (render-pass-encoder wgpu-render-pass-encoder))

(defcfun ("wgpuRenderPassEncoderRelease" wgpu-render-pass-encoder-release) :void
  (render-pass-encoder wgpu-render-pass-encoder))

(defcfun ("wgpuRenderPipelineGetBindGroupLayout" wgpu-render-pipeline-get-bind-group-layout) wgpu-bind-group-layout
  (render-pipeline wgpu-render-pipeline)
  (group-index :uint32))

;; NOTE: wgpu-render-pipeline-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuRenderPipelineAddRef" wgpu-render-pipeline-add-ref) :void
  (render-pipeline wgpu-render-pipeline))

(defcfun ("wgpuRenderPipelineRelease" wgpu-render-pipeline-release) :void
  (render-pipeline wgpu-render-pipeline))

;; NOTE: wgpu-sampler-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuSamplerAddRef" wgpu-sampler-add-ref) :void
  (sampler wgpu-sampler))

(defcfun ("wgpuSamplerRelease" wgpu-sampler-release) :void
  (sampler wgpu-sampler))

;; NOTE: wgpu-shader-module-get-compilation-info skipped (returns WGPUFuture by value) - use shim

;; NOTE: wgpu-shader-module-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuShaderModuleAddRef" wgpu-shader-module-add-ref) :void
  (shader-module wgpu-shader-module))

(defcfun ("wgpuShaderModuleRelease" wgpu-shader-module-release) :void
  (shader-module wgpu-shader-module))

;; NOTE: wgpu-supported-features-free-members skipped (param supportedFeatures is WGPUSupportedFeatures by value) - use shim

;; NOTE: wgpu-supported-instance-features-free-members skipped (param supportedInstanceFeatures is WGPUSupportedInstanceFeatures by value) - use shim

;; NOTE: wgpu-supported-wgsl-language-features-free-members skipped (param supportedWGSLLanguageFeatures is WGPUSupportedWGSLLanguageFeatures by value) - use shim

(defcfun ("wgpuSurfaceConfigure" wgpu-surface-configure) :void
  (surface wgpu-surface)
  (config :pointer))

(defcfun ("wgpuSurfaceGetCapabilities" wgpu-surface-get-capabilities) wgpu-status
  (surface wgpu-surface)
  (adapter wgpu-adapter)
  (capabilities :pointer))

(defcfun ("wgpuSurfaceGetCurrentTexture" wgpu-surface-get-current-texture) :void
  (surface wgpu-surface)
  (surface-texture :pointer))

(defcfun ("wgpuSurfacePresent" wgpu-surface-present) wgpu-status
  (surface wgpu-surface))

;; NOTE: wgpu-surface-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuSurfaceUnconfigure" wgpu-surface-unconfigure) :void
  (surface wgpu-surface))

(defcfun ("wgpuSurfaceAddRef" wgpu-surface-add-ref) :void
  (surface wgpu-surface))

(defcfun ("wgpuSurfaceRelease" wgpu-surface-release) :void
  (surface wgpu-surface))

;; NOTE: wgpu-surface-capabilities-free-members skipped (param surfaceCapabilities is WGPUSurfaceCapabilities by value) - use shim

(defcfun ("wgpuTextureCreateView" wgpu-texture-create-view) wgpu-texture-view
  (texture wgpu-texture)
  (descriptor :pointer))

(defcfun ("wgpuTextureDestroy" wgpu-texture-destroy) :void
  (texture wgpu-texture))

(defcfun ("wgpuTextureGetDepthOrArrayLayers" wgpu-texture-get-depth-or-array-layers) :uint32
  (texture wgpu-texture))

(defcfun ("wgpuTextureGetDimension" wgpu-texture-get-dimension) wgpu-texture-dimension
  (texture wgpu-texture))

(defcfun ("wgpuTextureGetFormat" wgpu-texture-get-format) wgpu-texture-format
  (texture wgpu-texture))

(defcfun ("wgpuTextureGetHeight" wgpu-texture-get-height) :uint32
  (texture wgpu-texture))

(defcfun ("wgpuTextureGetMipLevelCount" wgpu-texture-get-mip-level-count) :uint32
  (texture wgpu-texture))

(defcfun ("wgpuTextureGetSampleCount" wgpu-texture-get-sample-count) :uint32
  (texture wgpu-texture))

(defcfun ("wgpuTextureGetTextureBindingViewDimension" wgpu-texture-get-texture-binding-view-dimension) wgpu-texture-view-dimension
  (texture wgpu-texture))

(defcfun ("wgpuTextureGetUsage" wgpu-texture-get-usage) wgpu-flags
  (texture wgpu-texture))

(defcfun ("wgpuTextureGetWidth" wgpu-texture-get-width) :uint32
  (texture wgpu-texture))

;; NOTE: wgpu-texture-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuTextureAddRef" wgpu-texture-add-ref) :void
  (texture wgpu-texture))

(defcfun ("wgpuTextureRelease" wgpu-texture-release) :void
  (texture wgpu-texture))

;; NOTE: wgpu-texture-view-set-label skipped (param label is WGPUStringView by value) - use shim

(defcfun ("wgpuTextureViewAddRef" wgpu-texture-view-add-ref) :void
  (texture-view wgpu-texture-view))

(defcfun ("wgpuTextureViewRelease" wgpu-texture-view-release) :void
  (texture-view wgpu-texture-view))

(defcfun ("wgpuGenerateReport" wgpu-generate-report) :void
  (instance wgpu-instance)
  (report :pointer))

(defcfun ("wgpuInstanceEnumerateAdapters" wgpu-instance-enumerate-adapters) :size
  (instance wgpu-instance)
  (options :pointer)
  (adapters :pointer))

(defcfun ("wgpuQueueSubmitForIndex" wgpu-queue-submit-for-index) :uint64
  (queue wgpu-queue)
  (command-count :size)
  (commands :pointer))

(defcfun ("wgpuQueueGetTimestampPeriod" wgpu-queue-get-timestamp-period) :float
  (queue wgpu-queue))

(defcfun ("wgpuDevicePoll" wgpu-device-poll) :pointer
  (device wgpu-device)
  (wait wgpu-bool)
  (submission-index :pointer))

(defcfun ("wgpuDeviceCreateShaderModuleSpirV" wgpu-device-create-shader-module-spir-v) wgpu-shader-module
  (device wgpu-device)
  (descriptor :pointer))

(defcfun ("wgpuSetLogCallback" wgpu-set-log-callback) :void
  (callback :pointer)
  (userdata :pointer))

(defcfun ("wgpuSetLogLevel" wgpu-set-log-level) :void
  (level wgpu-log-level))

(defcfun ("wgpuGetVersion" wgpu-get-version) :uint32)

(defcfun ("wgpuDeviceGetNativeMetalDevice" wgpu-device-get-native-metal-device) :pointer
  (device wgpu-device))

(defcfun ("wgpuQueueGetNativeMetalCommandQueue" wgpu-queue-get-native-metal-command-queue) :pointer
  (queue wgpu-queue))

(defcfun ("wgpuTextureGetNativeMetalTexture" wgpu-texture-get-native-metal-texture) :pointer
  (texture wgpu-texture))

(defcfun ("wgpuRenderPassEncoderMultiDrawIndirect" wgpu-render-pass-encoder-multi-draw-indirect) :pointer
  (encoder wgpu-render-pass-encoder)
  (buffer wgpu-buffer)
  (offset :uint64)
  (count :uint32))

(defcfun ("wgpuRenderPassEncoderMultiDrawIndexedIndirect" wgpu-render-pass-encoder-multi-draw-indexed-indirect) :void
  (encoder wgpu-render-pass-encoder)
  (buffer wgpu-buffer)
  (offset :uint64)
  (count :uint32))

(defcfun ("wgpuRenderPassEncoderMultiDrawIndirectCount" wgpu-render-pass-encoder-multi-draw-indirect-count) :void
  (encoder wgpu-render-pass-encoder)
  (buffer wgpu-buffer)
  (offset :uint64)
  (count_buffer wgpu-buffer)
  (count_buffer_offset :uint64)
  (max_count :uint32))

(defcfun ("wgpuRenderPassEncoderMultiDrawIndexedIndirectCount" wgpu-render-pass-encoder-multi-draw-indexed-indirect-count) :void
  (encoder wgpu-render-pass-encoder)
  (buffer wgpu-buffer)
  (offset :uint64)
  (count_buffer wgpu-buffer)
  (count_buffer_offset :uint64)
  (max_count :uint32))

(defcfun ("wgpuComputePassEncoderBeginPipelineStatisticsQuery" wgpu-compute-pass-encoder-begin-pipeline-statistics-query) :void
  (compute-pass-encoder wgpu-compute-pass-encoder)
  (query-set wgpu-query-set)
  (query-index :uint32))

(defcfun ("wgpuComputePassEncoderEndPipelineStatisticsQuery" wgpu-compute-pass-encoder-end-pipeline-statistics-query) :void
  (compute-pass-encoder wgpu-compute-pass-encoder))

(defcfun ("wgpuRenderPassEncoderBeginPipelineStatisticsQuery" wgpu-render-pass-encoder-begin-pipeline-statistics-query) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (query-set wgpu-query-set)
  (query-index :uint32))

(defcfun ("wgpuRenderPassEncoderEndPipelineStatisticsQuery" wgpu-render-pass-encoder-end-pipeline-statistics-query) :void
  (render-pass-encoder wgpu-render-pass-encoder))

(defcfun ("wgpuComputePassEncoderWriteTimestamp" wgpu-compute-pass-encoder-write-timestamp) :void
  (compute-pass-encoder wgpu-compute-pass-encoder)
  (query-set wgpu-query-set)
  (query-index :uint32))

(defcfun ("wgpuRenderPassEncoderWriteTimestamp" wgpu-render-pass-encoder-write-timestamp) :void
  (render-pass-encoder wgpu-render-pass-encoder)
  (query-set wgpu-query-set)
  (query-index :uint32))

(defcfun ("wgpuDeviceStartGraphicsDebuggerCapture" wgpu-device-start-graphics-debugger-capture) :pointer
  (device wgpu-device))

(defcfun ("wgpuDeviceStopGraphicsDebuggerCapture" wgpu-device-stop-graphics-debugger-capture) :void
  (device wgpu-device))

(defcfun ("wgpuCommandEncoderClearTexture" wgpu-command-encoder-clear-texture) :void
  (command-encoder wgpu-command-encoder)
  (texture wgpu-texture)
  (range :pointer))
